import { NextSeo } from 'next-seo';
import '@safer/slick.css';
import '@safer/animate.css';
import '@safer/nice-select.css';
import '@safer/jquery.nice-number.min.css';
import '@safer/magnific-popup.css';
import '@safer/bootstrap.min.css';
import '@safer/font-awesome.min.css';
import '@safer/default.css';
import '@safer/style.css';
import '@safer/responsive.css';
export default function Head() {
  return (
    <>
      <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width" />
       
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <link rel="shortcut icon" href="images/favicon.png" type="image/png"/>
  
    </>
  )
}
